<?php

$counties = [
  "Bedfordshire",
  "Berkshire",
  "Blackburn With Darwen",
  "Blackpool",
  "Blaenau Gwent",
  "Bournemouth",
  "Bournemouth, Christchurch And Poole",
  "Bracknell Forest",
  "Bridgend",
  "Brighton And Hove",
  "Buckinghamshire",
  "Caerphilly",
  "Cambridgeshire",
  "Cardiff",
  "Carmarthenshire",
  "Central Bedfordshire",
  "Ceredigion",
  "Cheshire",
  "Cheshire East",
  "Cheshire West And Chester",
  "City Of Bristol",
  "City Of Derby",
  "City Of Kingston Upon Hull",
  "City Of Nottingham",
  "City Of Peterborough",
  "City Of Plymouth",
  "Cleveland",
  "Clwyd",
  "Conwy",
  "Cornwall",
  "County Durham",
  "Cumbria",
  "Darlington",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "Dyfed",
  "East Riding Of Yorkshire",
  "East Sussex",
  "Essex",
  "Flintshire",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Gwent",
  "Gwynedd",
  "Halton",
  "Hampshire",
  "Hartlepool",
  "Hereford And Worcester",
  "Herefordshire",
  "Hertfordshire",
  "Humberside",
  "Isle Of Anglesey",
  "Isle Of Wight",
  "Isles Of Scilly",
  "Kent",
  "Lancashire",
  "Leicester",
  "Leicestershire",
  "Lincolnshire",
  "Luton",
  "Medway",
  "Merseyside",
  "Merthyr Tydfil",
  "Mid Glamorgan",
  "Middlesbrough",
  "Milton Keynes",
  "Monmouthshire",
  "Neath Port Talbot",
  "Newport",
  "Norfolk",
  "North East Lincolnshire",
  "North Lincolnshire",
  "North Somerset",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Oxfordshire",
  "Pembrokeshire",
  "Poole",
  "Portsmouth",
  "Powys",
  "Reading",
  "Redcar And Cleveland",
  "Rhondda Cynon Taff",
  "Rutland",
  "Shropshire",
  "Slough",
  "Somerset",
  "South Glamorgan",
  "South Gloucestershire",
  "South Yorkshire",
  "Southampton",
  "Southend-on-sea",
  "Staffordshire",
  "Stockton-on-tees",
  "Stoke-on-trent",
  "Suffolk",
  "Surrey",
  "Swansea",
  "Swindon",
  "Thamesdown",
  "The Vale Of Glamorgan",
  "Thurrock",
  "Torbay",
  "Torfaen",
  "Tyne And Wear",
  "Warrington",
  "Warwickshire",
  "West Berkshire",
  "West Glamorgan",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Windsor And Maidenhead",
  "Wokingham",
  "Worcestershire",
  "Wrekin",
  "Wrexham",
  "York"
];
